# Generated by CMake 2.8.12.2

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget Poco::Net)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target Poco::Net
add_library(Poco::Net SHARED IMPORTED)

set_target_properties(Poco::Net PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "POCO_NO_AUTOMATIC_LIBS"
  INTERFACE_INCLUDE_DIRECTORIES "D:/Development/op3d_active/poco-1.7.5/Net/include"
  INTERFACE_LINK_LIBRARIES "Poco::Foundation;ws2_32.lib;iphlpapi.lib"
)

# Import target "Poco::Net" for configuration "Debug"
set_property(TARGET Poco::Net APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(Poco::Net PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Development/op3d_active/poco-1.7.5/msvc/lib/Debug/PocoNetd.lib"
  IMPORTED_LOCATION_DEBUG "D:/Development/op3d_active/poco-1.7.5/msvc/bin/Debug/PocoNetd.dll"
  )

# Import target "Poco::Net" for configuration "Release"
set_property(TARGET Poco::Net APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Poco::Net PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Development/op3d_active/poco-1.7.5/msvc/lib/Release/PocoNet.lib"
  IMPORTED_LOCATION_RELEASE "D:/Development/op3d_active/poco-1.7.5/msvc/bin/Release/PocoNet.dll"
  )

# Import target "Poco::Net" for configuration "MinSizeRel"
set_property(TARGET Poco::Net APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(Poco::Net PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "D:/Development/op3d_active/poco-1.7.5/msvc/lib/MinSizeRel/PocoNet.lib"
  IMPORTED_LOCATION_MINSIZEREL "D:/Development/op3d_active/poco-1.7.5/msvc/bin/MinSizeRel/PocoNet.dll"
  )

# Import target "Poco::Net" for configuration "RelWithDebInfo"
set_property(TARGET Poco::Net APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(Poco::Net PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "D:/Development/op3d_active/poco-1.7.5/msvc/lib/RelWithDebInfo/PocoNet.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/Development/op3d_active/poco-1.7.5/msvc/bin/RelWithDebInfo/PocoNet.dll"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
