# Generated by CMake 2.8.12.2

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget Poco::JSON)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target Poco::JSON
add_library(Poco::JSON SHARED IMPORTED)

set_target_properties(Poco::JSON PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "POCO_NO_AUTOMATIC_LIBS"
  INTERFACE_INCLUDE_DIRECTORIES "D:/Development/op3d_active/poco-1.7.5/JSON/include"
  INTERFACE_LINK_LIBRARIES "Poco::Foundation"
)

# Import target "Poco::JSON" for configuration "Debug"
set_property(TARGET Poco::JSON APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(Poco::JSON PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Development/op3d_active/poco-1.7.5/msvc/lib/Debug/PocoJSONd.lib"
  IMPORTED_LOCATION_DEBUG "D:/Development/op3d_active/poco-1.7.5/msvc/bin/Debug/PocoJSONd.dll"
  )

# Import target "Poco::JSON" for configuration "Release"
set_property(TARGET Poco::JSON APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Poco::JSON PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Development/op3d_active/poco-1.7.5/msvc/lib/Release/PocoJSON.lib"
  IMPORTED_LOCATION_RELEASE "D:/Development/op3d_active/poco-1.7.5/msvc/bin/Release/PocoJSON.dll"
  )

# Import target "Poco::JSON" for configuration "MinSizeRel"
set_property(TARGET Poco::JSON APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(Poco::JSON PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "D:/Development/op3d_active/poco-1.7.5/msvc/lib/MinSizeRel/PocoJSON.lib"
  IMPORTED_LOCATION_MINSIZEREL "D:/Development/op3d_active/poco-1.7.5/msvc/bin/MinSizeRel/PocoJSON.dll"
  )

# Import target "Poco::JSON" for configuration "RelWithDebInfo"
set_property(TARGET Poco::JSON APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(Poco::JSON PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "D:/Development/op3d_active/poco-1.7.5/msvc/lib/RelWithDebInfo/PocoJSON.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/Development/op3d_active/poco-1.7.5/msvc/bin/RelWithDebInfo/PocoJSON.dll"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
